{{- if and .Values.secretEnv.create (not .Values.secretEnv.existingSecret) -}}
{{- $fullName := default .Chart.Name .Values.fullnameOverride -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secret-env" $fullName }}
  labels:
    app.kubernetes.io/name: {{ $fullName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name (.Chart.Version | replace "+" "_") }}
type: {{ .Values.secretEnv.type }}
stringData:
  {{- range $key, $value := .Values.secretEnv.stringData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
